#!/usr/bin/env bash
# journal sync — wire this to a cron job to back up notes to your git remote.
#
# It pushes when the repo is ahead of its remote, pulls and re-indexes when
# behind, and auto-merges a divergence (preferring the remote on conflict). With
# no remote configured it does nothing. All the real work lives in `journal
# sync`; this wrapper just locates the repo and the binary so cron can call it.
#
# Generated by `journal init`. Safe to re-run / regenerate. See the repo README
# for cron setup on macOS and Linux.
set -euo pipefail

# The repo root is the parent of this script's .journal/ directory, regardless
# of where cron invokes it from.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

# Allow overriding the binary (e.g. JOURNAL_BIN=/usr/local/bin/journal) for cron
# environments with a minimal PATH.
JOURNAL_BIN="${JOURNAL_BIN:-journal}"

if ! command -v "${JOURNAL_BIN}" >/dev/null 2>&1; then
  echo "journal-sync: '${JOURNAL_BIN}' not found on PATH; set JOURNAL_BIN to its full path" >&2
  exit 127
fi

cd "${repo_root}"
exec "${JOURNAL_BIN}" sync "$@"
